{{- range .Values.spock.clusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-superuser
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ $.Values.spock.superuser.password | quote }}
---
{{- end }}

